name: sharesquare
description: A modern roommate & flatshare management app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Navigation
  go_router: ^13.2.0

  # UI & Fonts
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

  # Charts
  fl_chart: ^0.67.0

  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

  # Icons
  cupertino_icons: ^1.0.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_dotenv: ^5.2.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
